
export type APP_NAME = "MM-BACKEND";
export const APP_KEY = 'MM-BACKEND';

export type ORDER_STATUS = 'WAITING' | 'CHECKED' | 'ERROR';
export const ALL_ORDER_STATUS = { WAITING: <ORDER_STATUS>"WAITING", CHECKED: <ORDER_STATUS>'CHECKED', ERROR: <ORDER_STATUS>'ERROR' };
export const ALL_ORDER_STATUS_ARR = [ALL_ORDER_STATUS.WAITING, ALL_ORDER_STATUS.CHECKED, ALL_ORDER_STATUS.ERROR];

export type BATCH_STATUS = 'WAITING' | 'CHECKED' | 'READY' | 'RUNNING' | 'COMPLETED' | 'ERROR';
export const ALL_BATCH_STATUS = { WAITING: <BATCH_STATUS>"WAITING", READY: <BATCH_STATUS>'READY', RUNNING: <BATCH_STATUS>'RUNNING', COMPLETED: <BATCH_STATUS>'COMPLETED', ERROR: <BATCH_STATUS>'ERROR', CHECKED: <BATCH_STATUS>'CHECKED' };
export const ALL_BATCH_STATUS_ARR = [ALL_BATCH_STATUS.WAITING, ALL_BATCH_STATUS.RUNNING, ALL_BATCH_STATUS.COMPLETED, ALL_BATCH_STATUS.READY];

export type BATCH_PAYMENT_METHOD = 'COD' | 'DEBT';
export const ALL_BATCH_PAYMENT_METHOD = { COD: <BATCH_PAYMENT_METHOD>'COD', DEBT: <BATCH_PAYMENT_METHOD>'DEBT' };
export const ALL_BATCH_PAYMENT_METHOD_ARR = [ALL_BATCH_PAYMENT_METHOD.COD, ALL_BATCH_PAYMENT_METHOD.DEBT];

export type BATCH_CATEGORY = 'DRY' | 'FROZEN';
export const ALL_BATCH_CATEGORY = { DRY: <BATCH_CATEGORY>'DRY', FROZEN: <BATCH_CATEGORY>'FROZEN' };
export const ALL_BATCH_CATEGORY_ARR = [ALL_BATCH_CATEGORY.FROZEN, ALL_BATCH_CATEGORY.DRY];

export type DELIVERYTRIP_STATUS = "WAITING" | "RUNNING" | "COMPLETED";
export const ALL_DELIVERYTRIP_STATUS = { WAITING: <DELIVERYTRIP_STATUS>"WAITING", RUNNING: <DELIVERYTRIP_STATUS>"RUNNING", COMPLETED: <DELIVERYTRIP_STATUS>"COMPLETED" }

export type USER_TYPE = 'SHIPPER' | 'MONITOR' | 'ACCOUNTANT' | 'KEY_IN';
export const ALL_USER_TYPE = { SHIPPER: <USER_TYPE>'SHIPPER', MONITOR: <USER_TYPE>'MONITOR', ACCOUNTANT: <USER_TYPE>'ACCOUNTANT', KEY_IN: <USER_TYPE>'KEY_IN' };
export const ALL_USER_TYPE_ARR = [ALL_USER_TYPE.SHIPPER, ALL_USER_TYPE.ACCOUNTANT, ALL_USER_TYPE.KEY_IN, ALL_USER_TYPE.MONITOR];


export type SHIPPER_STATUS = 'AVAILABLE' | 'UNAVAILABLE';
export const ALL_SHIPPER_STATUS = { AVAILABLE: <SHIPPER_STATUS>'AVAILABLE', UNAVAILABLE: <SHIPPER_STATUS>'UNAVAILABLE' };
export const ALL_SHIPPER_STATUS_ARR = [ALL_SHIPPER_STATUS.AVAILABLE, ALL_SHIPPER_STATUS.UNAVAILABLE];

export type TRUCK_STATUS = 'AVAILABLE' | 'UNAVAILABLE';
export const ALL_TRUCK_STATUS = { AVAILABLE: <SHIPPER_STATUS>'AVAILABLE', UNAVAILABLE: <SHIPPER_STATUS>'UNAVAILABLE' };
export const ALL_TRUCK_STATUS_ARR = [ALL_SHIPPER_STATUS.AVAILABLE, ALL_SHIPPER_STATUS.UNAVAILABLE];